### ISSUE TITLE
Missing item flags of added items

### ISSUE THREAD

**Issue by poetter-sebastian** [augentism/NewWorldCrops#2]
Hello, I like the idea of the mod! I work on a gardener class and it would be nice if you add [item flags](https://github.com/anegostudios/vsapi/blob/bb282422038ad301639d1ef51d519c990d22543d/Common/Collectible/Item/EnumItemStorageFlags.cs) to your [seeds, plants and food](https://github.com/augentism/NewWorldCrops/tree/master/assets/assets/newworldcrops/itemtypes), so they support filtering and could be stored in specialized bags (like the [miner bag](https://wiki.vintagestory.at/index.php/Mining_bag))

You just have to add `"storageFlags": X` to your json objects.
For example:
```json
{
    "code": "vegetable",
    "storageFlags": 33,
	"maxstacksize": 64,
	"variantgroups": [
		{
			"code": "type",
			"states": ["potato", "tomato"]
		}
	],
    ....
}
```
(The number 33 contains the flag 1 for general and 32 for farming related stuff.)

Keep up the good work and thanks!

**Comment by augentism** [comment]
ah, i see, thats a good idea. didnt know that was a thing, but i will roll this into the next update. im a bit busy right now with classes, but i think i can get a release done by the end of the week.

**Comment by augentism** [comment]
Should be added in the most recent release 0.0.4 on the mod page. let me know if anything is improperly tagged or missing.
