### ISSUE TITLE
[Warning] on Server-Startup.

### ISSUE THREAD

**Issue by NiemandNatural** [augentism/NewWorldCrops#4]
Server is throwing warnings on startup:
```
5.5.2024 01:02:37 [Warning] Block patch Nr. 79: Unable to resolve block with code newworldcrops:crop-pepper-13. Will ignore.
5.5.2024 01:02:37 [Warning] Block patch Nr. 80: Unable to resolve block with code newworldcrops:crop-tomato-13. Will ignore.
```

Using augplantlib 0.0.3
and NewWorldCrops 0.0.6
on VS 1.19.7

Tomatoes are disgusting anyways. :P

**Comment by augentism** [comment]
Ah I see the issue. It's been fixed in commit 2acf7231f99149d638fe31002168ca78866caa72 for the next update. This bug will make the tomato and pepper plants spawn rate slightly rarer, but otherwise should function as normal and can be safely ignored until then.

Thanks for reporting.
